### ISSUE TITLE
Настройка параметров модели

### ISSUE THREAD

**Issue by kirillkoncha** [ai-forever/gigachat#12]
Добрый день!

Хотел спросить подсказку, как можно настраивать дополнительные параметры модели типа температуры и т.д. Нашел в коде класс `BaseSettings`, но не понял как задействовать его в классе `GigaChat` (так как он не имеет параметров настройки, кроме выбора модели).

Буду благодарен за помощь!

**Comment by Rai220** [comment]
Добрый день! Посмотрите в этом классе - тут все параметры описаны, которые можно настроить
https://github.com/ai-forever/gigachat/blob/main/src/gigachat/models/chat.py
