### ISSUE TITLE
Список моделей

### ISSUE THREAD

**Issue by David3456789** [ai-forever/gigachat#2]
Здравствуйте, подскажите пожалуйста, где можно посмотреть актуальный список версий гигачат доступных через api и как можно указать тип модели, которую нужно использовать в python. При запросе списка моделей через объект клиента возвращается только две модели:
![image](https://github.com/ai-forever/gigachat/assets/51019062/086ba3e0-818d-4930-90e2-3435e0d7310b)

Меня также особенно сильно интересует, как получить доступ к модели с улучшенной генерацией json, выпуск которой вы недавно анонсировали.

**Comment by Rai220** [comment]
Попробуйте модель GigaChat-Pro. Она во всем лучше, в том числе и в работе с json.
