### ISSUE TITLE
Можно ли задействовать GigaChat, в качестве агента в Autogen?

### ISSUE THREAD

**Issue by qSerj** [ai-forever/gigachat#6]
На первый взгляд нет проблем. Но не получается выполнить авторизацию, получить токен доступа и далее сопровождать им запросы, в рамках их агента реализующего протокол взаимодействия OpenAI.

**Comment by Rai220** [comment]
Думаю, можно подключить GigaChat к AutoGen с помощью GigaChain по этой статье - https://blog.gopenai.com/autogen-langchain-chromadb-super-ai-agents-d16002f83607

Я попробую это сделать и если получится - дополню в инструкции gigachain.
Сам gigachat синхронизировать с openai с точки зрения API пока не планировали.

**Comment by Rai220** [comment]
Вопрос интересный, изучу

**Comment by Rai220** [comment]
Да, к сожалению API GigaChat похож на OpenAI, но не имеет 100% совместимости. Простого пути прикрутить не вижу, разве что делать какой-то прокси. 

Можно вот на этот проект посмотреть - он совместим с GigaChain: https://github.com/joaomdmoura/crewai
